# Generated by Django 5.0.2 on 2024-03-18 10:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("Birthday", "День рождения"),
                            ("Wedding", "Свадьба"),
                            ("Charity", "Благотворительность"),
                            ("Travel", "Путешествие"),
                            ("Date", "Свидание"),
                            ("Education", "Оплата обучения или курсов"),
                            ("Gift", "Подарок"),
                            ("SportsEvent", "Спортивное соревнование"),
                            ("MedicalTreatment", "Медицинское лечение"),
                            ("DisasterRecovery", "Восстановление после бедствия"),
                            ("Other", "Другое"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("goal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "current_sum",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("cover", models.ImageField(upload_to="media/covers/")),
                (
                    "deadline",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 4, 1, 17, 16, 23, 709692)
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Денежный сбор",
                "verbose_name_plural": "Денежные сборы",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "collect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donation.collect",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "ordering": ["timestamp"],
            },
        ),
    ]
